# Generated by Django 5.2.3 on 2025-12-06 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_duration_mins_alter_event_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='discount_perc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
