# Generated by Django 5.2.3 on 2025-12-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_ticket_discount_perc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_meet_link',
        ),
        migrations.CreateModel(
            name='VirtualMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(choices=[('meet', 'Google Meet'), ('jitsi', 'Jitsi')], max_length=20)),
                ('join_url', models.URLField(max_length=500)),
                ('external_calendar_event_id', models.CharField(blank=True, help_text="The ID of the event in the provider's calendar (Google/Outlook)", max_length=255, null=True)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_meeting', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
