# Generated by Django 5.2.3 on 2025-12-20 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_google_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
