# Generated by Django 5.2.3 on 2026-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_type_ticketpurchase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
