# Generated by Django 5.2.3 on 2025-09-19 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('matric_no', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=20)),
                ('level', models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')])),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('skills', models.JSONField(default=list)),
                ('expected_grad_year', models.CharField(max_length=4)),
                ('preferred_industry', models.CharField()),
                ('preferred_company_type', models.CharField()),
                ('willingness_to_relocate', models.BooleanField()),
                ('willingness_to_be_mentored', models.BooleanField(default=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('x_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
