# Generated by Django 5.2.3 on 2025-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='willingness_to_relocate',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_company_type',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_industry',
            field=models.CharField(blank=True, null=True),
        ),
    ]
