# Generated by Django 5.2.3 on 2025-12-06 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentprofile_willingness_to_relocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default='Akure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='firstname',
            field=models.CharField(default='Covenant', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other'), ('Unknown', 'unknown')], default=datetime.datetime(2025, 12, 6, 7, 39, 51, 557716, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='lastname',
            field=models.CharField(default='Adeosun', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_num',
            field=models.CharField(default='09069189724'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(default='Ondo', max_length=20),
            preserve_default=False,
        ),
    ]
