# Generated by Django 5.2.3 on 2025-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofileimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Ekute Quaters, Ado Ekiti', max_length=225),
            preserve_default=False,
        ),
    ]
