# Generated by Django 5.2.3 on 2025-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_address_remove_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
