# Generated by Django 5.2.3 on 2025-09-27 23:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_internship_deleted_at_internship_is_deleted'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='accepted',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Withdrawn', 'withdrawn')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='InternResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', cloudinary.models.CloudinaryField(max_length=255, verbose_name='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='students.studentprofile')),
            ],
        ),
    ]
