# Generated by Django 5.2.3 on 2025-10-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_remove_internshipapplication_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internresume',
            name='resume',
            field=models.URLField(),
        ),
    ]
