# Generated by Django 5.2.3 on 2025-10-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_alter_internresume_resume'),
        ('students', '0002_studentresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentresume'),
        ),
        migrations.DeleteModel(
            name='InternResume',
        ),
    ]
