# Generated by Django 5.2.3 on 2025-10-29 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0006_remove_internshipapplication_responded_at_and_more'),
        ('students', '0003_remove_studentprofile_willingness_to_relocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationresume',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_resumes', to='students.studentprofile'),
        ),
    ]
