# Generated by Django 5.2.3 on 2025-10-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0007_applicationresume_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipapplication',
            old_name='updated_at',
            new_name='responded_at',
        ),
    ]
