# Generated by Django 5.2.3 on 2025-10-30 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0008_rename_updated_at_internshipapplication_responded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='responded_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
