# Generated by Django 5.2.3 on 2025-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0010_internshipoffer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='remaining_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
