# Generated by Django 5.2.3 on 2025-09-14 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('matric_no', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=30)),
                ('faculty', models.CharField(max_length=20)),
                ('grad_year', models.CharField(max_length=4)),
                ('current_job_title', models.CharField()),
                ('current_company', models.CharField()),
                ('industry', models.CharField()),
                ('years_of_exp', models.IntegerField()),
                ('previous_comps', models.JSONField(blank=True, default=list, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('x_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
