# Generated by Django 5.2.3 on 2025-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='matric_no',
            field=models.CharField(max_length=15),
        ),
    ]
