# Generated by Django 5.2.3 on 2025-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnus', '0003_alter_alumniprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='company_linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='company_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='matric_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
