# Generated by Django 5.2.3 on 2025-12-06 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnus', '0004_alumniprofile_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='address',
            field=models.CharField(default='Akure', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='country',
            field=models.CharField(default='Nigeria', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='firstname',
            field=models.CharField(default='Covenant', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other'), ('Unknown', 'unknown')], default='male'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2025, 12, 6, 7, 38, 6, 922583, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='phone_num',
            field=models.CharField(default='09069189724'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='state',
            field=models.CharField(default='Ondo', max_length=20),
            preserve_default=False,
        ),
    ]
