# Generated by Django 5.2.3 on 2025-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnus', '0005_alumniprofile_address_alumniprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')]),
        ),
    ]
