# Generated by Django 5.2.3 on 2025-11-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipoffer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='remaining_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='cover_letter',
            field=models.TextField(default='string'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorshipapplication',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
