# Generated by Django 5.2.3 on 2025-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0002_remove_mentorshipoffer_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipengagement',
            name='updated_at',
        ),
    ]
