# Generated by Django 5.2.3 on 2025-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorships', '0003_remove_mentorshipengagement_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='available_slots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
